In [1]:
import numpy as np
import pandas as pd
import openpyxl
import statsmodels.api as sm
import datetime
from statsmodels.stats.outliers_influence import variance_inflation_factor as vif

データフレーム準備

In [2]:
Cost_df = pd.read_excel('SSDSE-B-2023.xlsx', 
                        skiprows=1,
                        names=['年度', '地域コード', '都道府県', '総人口', '総人口（男）', '総人口（女）', '日本人人口', '日本人人口（男）', '日本人人口（女）', '15歳未満人口', '15歳未満人口（男）', '15歳未満人口（女）', '15～64歳人口', '15～64歳人口（男）', '15～64歳人口（女）', '65歳以上人口', '65歳以上人口（男）', '65歳以上人口（女）', '出生数', '出生数（男）', '出生数（女）', '合計特殊出生率', '死亡数', '死亡数（男）', '死亡数（女）', '転入者数（日本人移動者）', '転入者数（日本人移動者）（男）', '転入者数（日本人移動者）（女）', '転出者数（日本人移動者）', '転出者数（日本人移動者）（男）', '転出者数（日本人移動者）（女）', '婚姻件数', '離婚件数', '年平均気温', '最高気温（日最高気温の月平均の最高値）', '最低気温（日最低気温の月平均の最低値）', '降水日数（年間）', '降水量（年間）', '着工建築物数', '着工建築物床面積', '旅館営業施設数（ホテルを含む）', '旅館営業施設客室数（ホテルを含む）', '標準価格（平均価格）（住宅地）', '標準価格（平均価格）（商業地）', '幼稚園数', '幼稚園教員数', '幼稚園在園者数', '小学校数', '小学校教員数', '小学校児童数', '中学校数', '中学校教員数', '中学校生徒数', '中学校卒業者数', '中学校卒業者のうち進学者数', '高等学校数', '高等学校教員数', '高等学校生徒数', '高等学校卒業者数', '高等学校卒業者のうち進学者数', '短期大学数', '大学数', '短期大学教員数', '大学教員数', '短期大学学生数', '大学学生数', '短期大学卒業者数', '短期大学卒業者のうち進学者数', '大学卒業者数', '大学卒業者のうち進学者数', '専修学校数', '各種学校数', '専修学校生徒数', '各種学校生徒数', '新規求職申込件数（一般）', '月間有効求職者数（一般）', '月間有効求人数（一般）', '充足数（一般）', '就職件数（一般）', '一般旅券発行件数', '延べ宿泊者数', '外国人延べ宿泊者数', '着工新設住宅戸数', '着工新設持家数', '着工新設貸家数', '着工新設分譲住宅数', '着工新設住宅床面積', '着工新設持家床面積', '着工新設分譲住宅床面積', '着工新設貸家床面積', 'ごみ総排出量（総量）', '1人1日当たりの排出量', 'ごみのリサイクル率', '一般病院数', '一般診療所数', '歯科診療所数', '保育所等数', '保育所等定員数', '保育所等利用待機児童数', '保育所等在所児数', '保育所等保育士数', '消費支出', '食料費', '住居費', '光熱・水道費', '家具・家事用品費', '被服及び履物費', '保健医療費', '交通・通信費', '教育費', '教養娯楽費', 'その他の消費支出'])
Cost_df = Cost_df[Cost_df['都道府県'] == '埼玉県']

Cost_df

,年度,地域コード,都道府県,総人口,総人口（男）,総人口（女）,日本人人口,日本人人口（男）,日本人人口（女）,15歳未満人口,...,食料費,住居費,光熱・水道費,家具・家事用品費,被服及び履物費,保健医療費,交通・通信費,教育費,教養娯楽費,その他の消費支出
119,2020,R11000,埼玉県,7344765,3652169,3692596,7055679,3516273,3539406,858384,...,84240,16200,21742,12063,11915,14721,55992,23246,31583,54611
120,2019,R11000,埼玉県,7342000,3657000,3685000,7166000,3569000,3597000,881000,...,85210,14156,23565,14163,14075,17413,44741,20381,39730,63848
121,2018,R11000,埼玉県,7325000,3650000,3675000,7171000,3575000,3595000,891000,...,81408,18833,23377,10949,13766,14733,46848,22673,33799,57545
122,2017,R11000,埼玉県,7307000,3643000,3664000,7171000,3580000,3592000,899000,...,78135,18810,21888,10776,12941,14764,41201,18107,29933,54785
123,2016,R11000,埼玉県,7288000,3637000,3652000,7168000,3580000,3587000,907000,...,80706,25480,23409,10412,14163,13973,46246,20114,38281,55973
124,2015,R11000,埼玉県,7266534,3628418,3638116,7111168,3553767,3557401,910805,...,80321,19285,25015,10310,14417,13144,43633,12157,36206,60899
125,2014,R11000,埼玉県,7247000,3621000,3626000,7151000,3579000,3572000,929000,...,78388,22771,25347,13310,16120,13097,44549,21754,36960,57152
126,2013,R11000,埼玉県,7228000,3614000,3614000,7140000,3576000,3564000,934000,...,74241,17449,24042,10585,13893,11745,41066,13896,39085,62735
127,2012,R11000,埼玉県,7216000,3612000,3604000,7130000,3574000,3555000,940000,...,72512,22164,23740,10680,14441,12152,37698,25131,32835,63527
128,2011,R11000,埼玉県,7209000,3612000,3597000,7119000,3573000,3546000,949000,...,75422,24121,23737,10590,14865,14391,33600,14256,40037,66819
129,2010,R11000,埼玉県,7194556,3608711,3585845,7054944,3540768,3514176,953668,...,73840,19566,24059,10077,13828,13952,38142,14997,42992,68368
130,2009,R11000,埼玉県,7161000,3597000,3565000,7074000,3557000,3516000,969000,...,77481,19701,23186,10877,16720,13598,38117,29916,44045,67921

データフレームの加工

In [3]:
columns_to_keep = ['食料費', '住居費', '光熱・水道費', '家具・家事用品費', '被服及び履物費', '保健医療費', '交通・通信費', '教育費', '教養娯楽費']
Cost_taeget_df = Cost_df.drop(columns=[col for col in Cost_df.columns if col not in columns_to_keep])
Cost_taeget_df = Cost_taeget_df.iloc[::-1]  # インデックスを逆順にする
Cost_taeget_df.reset_index(drop=True, inplace=True)

Cost_taeget_df

      食料費    住居費  光熱・水道費  家具・家事用品費  被服及び履物費  保健医療費  交通・通信費    教育費  教養娯楽費
0   77481  19701   23186     10877    16720  13598   38117  29916  44045
1   73840  19566   24059     10077    13828  13952   38142  14997  42992
2   75422  24121   23737     10590    14865  14391   33600  14256  40037
3   72512  22164   23740     10680    14441  12152   37698  25131  32835
4   74241  17449   24042     10585    13893  11745   41066  13896  39085
5   78388  22771   25347     13310    16120  13097   44549  21754  36960
6   80321  19285   25015     10310    14417  13144   43633  12157  36206
7   80706  25480   23409     10412    14163  13973   46246  20114  38281
8   78135  18810   21888     10776    12941  14764   41201  18107  29933
9   81408  18833   23377     10949    13766  14733   46848  22673  33799
10  85210  14156   23565     14163    14075  17413   44741  20381  39730
11  84240  16200   21742     12063    11915  14721   55992  23246  31583

教育費を対象に重回帰分析

In [4]:
#目的変数
target = '教育費'
y = Cost_taeget_df[target].astype(np.float32)

# 説明変数
explanation = list(filter(lambda x: x != target, columns_to_keep))
x = Cost_taeget_df[explanation].astype(np.float32)
x_added_constant = sm.add_constant(x)

# 重回帰分析を実施、独立変数間の分散拡大要因を確認後、分析結果を出力
model = sm.OLS(y, x_added_constant)
num_cols = model.exog.shape[1] # 説明変数の列数
vifs = [vif(model.exog, i) for i in range(0, num_cols)]
print(f'### 対象：{target} ###')
print(pd.DataFrame(vifs, index=model.exog_names, columns=['VIF']))

### 対象：教育費 ###
                  VIF
const     1673.338759
食料費         20.308455
住居費          2.135455
光熱・水道費       2.435451
家具・家事用品費     4.430627
被服及び履物費      7.177291
保健医療費       13.636377
交通・通信費      15.623027
教養娯楽費        2.739178

食糧費を除外

In [5]:
columns_to_keep = ['住居費', '光熱・水道費', '家具・家事用品費', '被服及び履物費', '保健医療費', '交通・通信費', '教育費', '教養娯楽費']
Cost_taeget_df = Cost_df.drop(columns=[col for col in Cost_df.columns if col not in columns_to_keep])
Cost_taeget_df = Cost_taeget_df.iloc[::-1]  # インデックスを逆順にする
Cost_taeget_df.reset_index(drop=True, inplace=True)

Cost_taeget_df

      住居費  光熱・水道費  家具・家事用品費  被服及び履物費  保健医療費  交通・通信費    教育費  教養娯楽費
0   19701   23186     10877    16720  13598   38117  29916  44045
1   19566   24059     10077    13828  13952   38142  14997  42992
2   24121   23737     10590    14865  14391   33600  14256  40037
3   22164   23740     10680    14441  12152   37698  25131  32835
4   17449   24042     10585    13893  11745   41066  13896  39085
5   22771   25347     13310    16120  13097   44549  21754  36960
6   19285   25015     10310    14417  13144   43633  12157  36206
7   25480   23409     10412    14163  13973   46246  20114  38281
8   18810   21888     10776    12941  14764   41201  18107  29933
9   18833   23377     10949    13766  14733   46848  22673  33799
10  14156   23565     14163    14075  17413   44741  20381  39730
11  16200   21742     12063    11915  14721   55992  23246  31583

重回帰分析を実行

In [6]:
# 目的変数
target = '教育費'
y = Cost_taeget_df[target].astype(np.float32)

# 説明変数
explanation = list(filter(lambda x: x != target, columns_to_keep))
x = Cost_taeget_df[explanation].astype(np.float32)
x_added_constant = sm.add_constant(x)

# 重回帰分析を実施、独立変数間の分散拡大要因を確認後、分析結果を出力
model = sm.OLS(y, x_added_constant)
num_cols = model.exog.shape[1] # 説明変数の列数
vifs = [vif(model.exog, i) for i in range(0, num_cols)]
print(f'### 対象：{target} ###')
print(pd.DataFrame(vifs, index=model.exog_names, columns=['VIF']))
print("\n")
result = model.fit()
print(result.summary())

### 対象：教育費 ###
                  VIF
const     1503.666813
住居費          1.890407
光熱・水道費       2.083546
家具・家事用品費     3.262498
被服及び履物費      3.793177
保健医療費        2.578339
交通・通信費       2.106794
教養娯楽費        2.312394


                            OLS Regression Results
==============================================================================
Dep. Variable:                    教育費   R-squared:                       0.743
Model:                            OLS   Adj. R-squared:                  0.293
Method:                 Least Squares   F-statistic:                     1.652
Date:                Thu, 20 Jul 2023   Prob (F-statistic):              0.328
Time:                        19:06:40   Log-Likelihood:                -111.18
No. Observations:                  12   AIC:                             238.4
Df Residuals:                       4   BIC:                             242.2
Df Model:                           7
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.465e+04   4.96e+04      1.103      0.332   -8.29e+04    1.92e+05
住居費           -0.0717      0.561     -0.128      0.904      -1.628       1.485
光熱・水道費        -4.4157      1.834     -2.408      0.074      -9.508       0.676
家具・家事用品費       0.7604      1.884      0.404      0.707      -4.471       5.992
被服及び履物費        4.4708      2.045      2.187      0.094      -1.206      10.147
保健医療費         -0.7061      1.462     -0.483      0.654      -4.765       3.352
交通・通信費         0.3485      0.334      1.042      0.356      -0.580       1.277
教養娯楽費         -0.1787      0.459     -0.390      0.717      -1.452       1.094
==============================================================================
Omnibus:                        1.422   Durbin-Watson:                   2.940
Prob(Omnibus):                  0.491   Jarque-Bera (JB):                0.926
Skew:                           0.636   Prob(JB):                        0.629
Kurtosis:                       2.519   Cond. No.                     2.65e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.65e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

c:\Users\human\DataScience_FEA\venv\Lib\site-packages\scipy\stats\_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=12
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "